/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: docs/api_inventory.json
 * Generated at: 2026-02-04T11:02:15.404Z
 *
 * To regenerate: npm run gen:api
 */
// @ts-nocheck

import { get, post, put, patch, del } from '@platform/http'
import type * as DTO from '@modules/agentos'

/**
 * Core AgentOS entities: Projects, Tasks, Repos, Sessions
 * 
 * Base path: /api/v0.31
 * Total endpoints: 15
 */
export const agentosServiceGen = {
  /**
   * List all projects with pagination
   */
  async listProjects(params?: DTO.ListProjectsRequest): Promise<DTO.ListProjectsResponse> {
    return get('/api/v0.31/projects', { params })
  },

  /**
   * Get project details by ID
   */
  async getProject(id: string): Promise<DTO.GetProjectResponse> {
    return get(`/api/v0.31/projects/${id}`)
  },

  /**
   * Create a new project
   */
  async createProject(data: DTO.CreateProjectRequest): Promise<DTO.CreateProjectResponse> {
    return post('/api/v0.31/projects', data)
  },

  /**
   * Update project
   */
  async updateProject(id: string, data: DTO.UpdateProjectRequest): Promise<DTO.UpdateProjectResponse> {
    return put(`/api/v0.31/projects/${id}`, data)
  },

  /**
   * Delete project
   */
  async deleteProject(id: string): Promise<void> {
    return del(`/api/v0.31/projects/${id}`)
  },

  /**
   * List tasks with filters
   */
  async listTasks(params?: DTO.ListTasksRequest): Promise<DTO.ListTasksResponse> {
    return get('/api/v0.31/tasks', { params })
  },

  /**
   * Get task by ID
   */
  async getTask(id: string): Promise<DTO.GetTaskResponse> {
    return get(`/api/v0.31/tasks/${id}`)
  },

  /**
   * Create a new task
   */
  async createTask(data: DTO.CreateTaskRequest): Promise<DTO.CreateTaskResponse> {
    return post('/api/v0.31/tasks', data)
  },

  /**
   * Update task
   */
  async updateTask(id: string, data: DTO.UpdateTaskRequest): Promise<DTO.UpdateTaskResponse> {
    return put(`/api/v0.31/tasks/${id}`, data)
  },

  /**
   * Delete task
   */
  async deleteTask(id: string): Promise<void> {
    return del(`/api/v0.31/tasks/${id}`)
  },

  /**
   * List repositories
   */
  async listRepos(params?: DTO.ListReposRequest): Promise<DTO.ListReposResponse> {
    return get('/api/v0.31/repos', { params })
  },

  /**
   * Get repository by ID
   */
  async getRepo(id: string): Promise<DTO.GetRepoResponse> {
    return get(`/api/v0.31/repos/${id}`)
  },

  /**
   * Create repository
   */
  async createRepo(data: DTO.CreateRepoRequest): Promise<DTO.CreateRepoResponse> {
    return post('/api/v0.31/repos', data)
  },

  /**
   * Update repository
   */
  async updateRepo(id: string, data: DTO.UpdateRepoRequest): Promise<DTO.UpdateRepoResponse> {
    return put(`/api/v0.31/repos/${id}`, data)
  },

  /**
   * Delete repository
   */
  async deleteRepo(id: string): Promise<void> {
    return del(`/api/v0.31/repos/${id}`)
  }
}
