/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: docs/api_inventory.json
 * Generated at: 2026-02-04T11:02:15.413Z
 *
 * To regenerate: npm run gen:api
 */

import { get, post, put, patch, del } from '@platform/http'
import type * as DTO from '@modules/appos'

/**
 * Application lifecycle management
 * 
 * Base path: /api
 * Total endpoints: 4
 */
export const apposServiceGen = {
  /**
   * List applications
   */
  async listApps(params?: DTO.ListAppsRequest): Promise<DTO.ListAppsResponse> {
    return get('/api/apps', { params })
  },

  /**
   * Get application details
   */
  async getApp(id: string): Promise<DTO.GetAppResponse> {
    return get(`/api/apps/${id}`)
  },

  /**
   * Start application
   */
  async startApp(id: string): Promise<void> {
    return post(`/api/apps/${id}/start`)
  },

  /**
   * Stop application
   */
  async stopApp(id: string): Promise<void> {
    return post(`/api/apps/${id}/stop`)
  }
}
