/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: docs/api_inventory.json
 * Generated at: 2026-02-04T11:02:15.410Z
 *
 * To regenerate: npm run gen:api
 */

import { get, post, put, patch, del } from '@platform/http'
import type * as DTO from '@modules/brainos'

/**
 * Knowledge management, decisions, review queue
 * 
 * Base path: /api
 * Total endpoints: 5
 */
export const brainosServiceGen = {
  /**
   * List knowledge sources
   */
  async listKnowledgeSources(params?: DTO.ListKnowledgeSourcesRequest): Promise<DTO.ListKnowledgeSourcesResponse> {
    return get('/api/knowledge/sources', { params })
  },

  /**
   * Create knowledge source
   */
  async createKnowledgeSource(data: DTO.CreateKnowledgeSourceRequest): Promise<DTO.CreateKnowledgeSourceResponse> {
    return post('/api/knowledge/sources', data)
  },

  /**
   * Get decision comparison data
   */
  async getDecisionComparison(params?: DTO.GetDecisionComparisonRequest): Promise<DTO.GetDecisionComparisonResponse> {
    return get('/api/v3/decision-comparison', { params })
  },

  /**
   * List review queue items
   */
  async listReviewQueue(params?: DTO.ListReviewQueueRequest): Promise<DTO.ListReviewQueueResponse> {
    return get('/api/v3/review-queue', { params })
  },

  /**
   * Get information need metrics
   */
  async getInfoNeedMetrics(): Promise<DTO.GetInfoNeedMetricsResponse> {
    return get('/api/info-need/metrics')
  }
}
