/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: docs/api_inventory.json
 * Generated at: 2026-02-04T11:02:15.412Z
 *
 * To regenerate: npm run gen:api
 */

import { get, post, put, patch, del } from '@platform/http'
import type * as DTO from '@modules/communicationos'

/**
 * Channels, sessions, voice, MCP
 * 
 * Base path: /api
 * Total endpoints: 5
 */
export const communicationosServiceGen = {
  /**
   * List communication channels
   */
  async listChannels(params?: DTO.ListChannelsRequest): Promise<DTO.ListChannelsResponse> {
    return get('/api/channels', { params })
  },

  /**
   * Create channel
   */
  async createChannel(data: DTO.CreateChannelRequest): Promise<DTO.CreateChannelResponse> {
    return post('/api/channels', data)
  },

  /**
   * List communication sessions
   */
  async listSessions(params?: DTO.ListSessionsRequest): Promise<DTO.ListSessionsResponse> {
    return get('/api/sessions', { params })
  },

  /**
   * List voice sessions
   */
  async listVoiceSessions(params?: DTO.ListVoiceSessionsRequest): Promise<DTO.ListVoiceSessionsResponse> {
    return get('/api/voice/sessions', { params })
  },

  /**
   * List MCP servers
   */
  async listMCPServers(params?: DTO.ListMCPServersRequest): Promise<DTO.ListMCPServersResponse> {
    return get('/api/mcp/servers', { params })
  }
}
