/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: docs/api_inventory.json
 * Generated at: 2026-02-04T11:02:15.408Z
 *
 * To regenerate: npm run gen:api
 */
// @ts-nocheck

import { get, post, put, patch, del } from '@platform/http'
import type * as DTO from '@modules/memoryos'

/**
 * Memory management: search, timeline, proposals
 * 
 * Base path: /api
 * Total endpoints: 5
 */
export const memoryosServiceGen = {
  /**
   * Search memories with filters
   */
  async searchMemories(data: DTO.SearchMemoryRequest): Promise<DTO.SearchMemoryResponse> {
    return post('/api/memory/search', data)
  },

  /**
   * Get memory timeline
   */
  async getMemoryTimeline(params?: DTO.GetTimelineRequest): Promise<DTO.GetTimelineResponse> {
    return get('/api/memory/timeline', { params })
  },

  /**
   * List memory proposals
   */
  async listMemoryProposals(params?: DTO.ListProposalsRequest): Promise<DTO.ListProposalsResponse> {
    return get('/api/memory/proposals', { params })
  },

  /**
   * Approve memory proposal
   */
  async approveMemoryProposal(id: string): Promise<void> {
    return post(`/api/memory/proposals/${id}/approve`)
  },

  /**
   * Reject memory proposal
   */
  async rejectMemoryProposal(id: string): Promise<void> {
    return post(`/api/memory/proposals/${id}/reject`)
  }
}
