/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: docs/api_inventory.json
 * Generated at: 2026-02-04T11:02:15.412Z
 *
 * To regenerate: npm run gen:api
 */

import { get, post, put, patch, del } from '@platform/http'
import type * as DTO from '@modules/networkos'

/**
 * Capabilities, governance, guardians, policies
 * 
 * Base path: /api
 * Total endpoints: 5
 */
export const networkosServiceGen = {
  /**
   * List capabilities
   */
  async listCapabilities(params?: DTO.ListCapabilitiesRequest): Promise<DTO.ListCapabilitiesResponse> {
    return get('/api/capabilities', { params })
  },

  /**
   * Get capability details
   */
  async getCapability(id: string): Promise<DTO.GetCapabilityResponse> {
    return get(`/api/capabilities/${id}`)
  },

  /**
   * Get governance dashboard
   */
  async getGovernanceDashboard(): Promise<DTO.GetGovernanceDashboardResponse> {
    return get('/api/governance/dashboard')
  },

  /**
   * List guardians
   */
  async listGuardians(params?: DTO.ListGuardiansRequest): Promise<DTO.ListGuardiansResponse> {
    return get('/api/guardians', { params })
  },

  /**
   * List execution policies
   */
  async listExecutionPolicies(params?: DTO.ListExecutionPoliciesRequest): Promise<DTO.ListExecutionPoliciesResponse> {
    return get('/api/execution-policies', { params })
  }
}
