/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: docs/api_inventory.json
 * Generated at: 2026-02-04T11:02:15.411Z
 *
 * To regenerate: npm run gen:api
 */
// @ts-nocheck

import { get, post, put, patch, del } from '@platform/http'
import type * as DTO from '@modules/skillos'

/**
 * Skills, extensions, templates, execution
 * 
 * Base path: /api
 * Total endpoints: 6
 */
export const skillosServiceGen = {
  /**
   * List installed skills
   */
  async listSkills(params?: DTO.ListSkillsRequest): Promise<DTO.ListSkillsResponse> {
    return get('/api/skills', { params })
  },

  /**
   * Get skill details
   */
  async getSkill(id: string): Promise<DTO.GetSkillResponse> {
    return get(`/api/skills/${id}`)
  },

  /**
   * Install a skill
   */
  async installSkill(data: DTO.InstallSkillRequest): Promise<DTO.InstallSkillResponse> {
    return post('/api/skills/install', data)
  },

  /**
   * List extensions
   */
  async listExtensions(params?: DTO.ListExtensionsRequest): Promise<DTO.ListExtensionsResponse> {
    return get('/api/extensions', { params })
  },

  /**
   * Enable extension
   */
  async enableExtension(id: string): Promise<void> {
    return post(`/api/extensions/${id}/enable`)
  },

  /**
   * Disable extension
   */
  async disableExtension(id: string): Promise<void> {
    return post(`/api/extensions/${id}/disable`)
  }
}
