/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: docs/api_inventory.json
 * Generated at: 2026-02-04T11:02:15.414Z
 *
 * To regenerate: npm run gen:api
 */

import { get, post, put, patch, del } from '@platform/http'
import type * as DTO from '@modules/system'

/**
 * System config, providers, models, health
 * 
 * Base path: /api
 * Total endpoints: 11
 */
export const systemServiceGen = {
  /**
   * Get system configuration
   */
  async getConfig(): Promise<DTO.GetConfigResponse> {
    return get('/api/config')
  },

  /**
   * Update system configuration
   */
  async updateConfig(data: DTO.UpdateConfigRequest): Promise<DTO.UpdateConfigResponse> {
    return put('/api/config', data)
  },

  /**
   * Health check endpoint
   */
  async healthCheck(): Promise<DTO.HealthCheckResponse> {
    return get('/api/health')
  },

  /**
   * List model providers
   */
  async listProviders(params?: DTO.ListProvidersRequest): Promise<DTO.ListProvidersResponse> {
    return get('/api/providers', { params })
  },

  /**
   * Get provider details
   */
  async getProvider(id: string): Promise<DTO.GetProviderResponse> {
    return get(`/api/providers/${id}`)
  },

  /**
   * Start provider
   */
  async startProvider(id: string): Promise<void> {
    return post(`/api/providers/${id}/start`)
  },

  /**
   * Stop provider
   */
  async stopProvider(id: string): Promise<void> {
    return post(`/api/providers/${id}/stop`)
  },

  /**
   * List available models
   */
  async listModels(params?: DTO.ListModelsRequest): Promise<DTO.ListModelsResponse> {
    return get('/api/models', { params })
  },

  /**
   * Pull/download a model
   */
  async pullModel(data: DTO.PullModelRequest): Promise<DTO.PullModelResponse> {
    return post('/api/models/pull', data)
  },

  /**
   * Get demo mode status
   */
  async getDemoModeStatus(): Promise<DTO.GetDemoModeStatusResponse> {
    return get('/api/demo/status')
  },

  /**
   * Toggle demo mode
   */
  async toggleDemoMode(data: DTO.ToggleDemoModeRequest): Promise<DTO.ToggleDemoModeResponse> {
    return post('/api/demo/toggle', data)
  }
}
