#!/usr/bin/env python3
"""Gate: ensure router contract+ artifacts are in sync and auditable."""

from __future__ import annotations

import difflib
import json
import tempfile
from pathlib import Path

from octopusos.core.chat.router_contract_plus import (
    GRAPH_PATH,
    SNAPSHOT_PATH,
    build_router_spec,
    generate_mermaid_graph,
    generate_route_order_snapshot,
    load_router_contract,
)

DIFF_REPORT_PATH = Path("reports/router_order_diff.md")


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_diff_report(diff_lines: list[str], old_snapshot: dict | None, new_snapshot: dict) -> None:
    DIFF_REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Router Order Diff",
        "",
        "Generated by `scripts/gates/verify_router_contract_plus.py`.",
        "",
    ]
    if old_snapshot is not None:
        old_order = [row.get("group_id") for row in old_snapshot.get("ordered_groups", [])]
    else:
        old_order = []
    new_order = [row.get("group_id") for row in new_snapshot.get("ordered_groups", [])]

    lines.append("## Ordered Groups (old -> new)")
    lines.append("")
    lines.append(f"- old: {old_order}")
    lines.append(f"- new: {new_order}")
    lines.append("")
    lines.append("## Unified Diff")
    lines.append("")
    lines.append("```diff")
    lines.extend(diff_lines)
    lines.append("```")
    lines.append("")
    DIFF_REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    contract = load_router_contract()
    spec = build_router_spec()
    generated_snapshot = generate_route_order_snapshot(contract, spec)
    generated_graph = generate_mermaid_graph(contract, spec)

    tracked_snapshot_exists = SNAPSHOT_PATH.exists()
    if not tracked_snapshot_exists:
        raise RuntimeError(
            f"missing tracked snapshot: {SNAPSHOT_PATH}. run update_router_contract_snapshot.py first"
        )

    tracked_snapshot = _read_json(SNAPSHOT_PATH)

    with tempfile.TemporaryDirectory(prefix="router-contract-plus-") as td:
        tmp_dir = Path(td)
        tmp_snapshot = tmp_dir / "router_route_order.snapshot.json"
        tmp_graph = tmp_dir / "router_graph.mmd"
        tmp_snapshot.write_text(
            json.dumps(generated_snapshot, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        tmp_graph.write_text(generated_graph, encoding="utf-8")

        tracked_text = SNAPSHOT_PATH.read_text(encoding="utf-8").splitlines()
        generated_text = tmp_snapshot.read_text(encoding="utf-8").splitlines()
        diff = list(
            difflib.unified_diff(
                tracked_text,
                generated_text,
                fromfile=str(SNAPSHOT_PATH),
                tofile=str(tmp_snapshot),
                lineterm="",
            )
        )

        if diff:
            _write_diff_report(diff, tracked_snapshot, generated_snapshot)
            contract_hash_old = str(tracked_snapshot.get("contract_hash") or "")
            contract_hash_new = str(generated_snapshot.get("contract_hash") or "")
            if contract_hash_old == contract_hash_new:
                raise RuntimeError(
                    "router order changed but contract hash unchanged; update contract first before refreshing snapshot. "
                    f"see {DIFF_REPORT_PATH}"
                )
            raise RuntimeError(
                "router contract+ snapshot drift detected; update contract+snapshot intentionally. "
                f"see {DIFF_REPORT_PATH}"
            )

        tracked_graph_exists = GRAPH_PATH.exists()
        if not tracked_graph_exists:
            raise RuntimeError(f"missing tracked graph: {GRAPH_PATH}")

        graph_diff = list(
            difflib.unified_diff(
                GRAPH_PATH.read_text(encoding="utf-8").splitlines(),
                tmp_graph.read_text(encoding="utf-8").splitlines(),
                fromfile=str(GRAPH_PATH),
                tofile=str(tmp_graph),
                lineterm="",
            )
        )
        if graph_diff:
            _write_diff_report(graph_diff, tracked_snapshot, generated_snapshot)
            raise RuntimeError(
                "router graph drift detected; refresh graph via update script. "
                f"see {DIFF_REPORT_PATH}"
            )

    print("router-contract-plus-gate: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
